### ISSUE TITLE
[ERROR] mergeRecursiveWithOverrule() must be of the type array, null given

### ISSUE THREAD

**Issue by denyskoch** [FluidTYPO3/flll#4] opened 2014-04-08 09:08 UTC
```
[Tue Apr 08 11:06:28 2014] [error] [client 192.168.56.6] FastCGI: server "/php-fpm-handler-koch" stderr: PHP message: http://***/ - Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1: PHP Catchable Fatal Error: Argument 1 passed to TYPO3\\CMS\\Core\\Utility\\ArrayUtility::mergeRecursiveWithOverrule() must be of the type array, null given, called in /home/shared_typo3/typo3_source/typo3_src-6.2.0/typo3/sysext/lang/Classes/LanguageService.php on line 463 and defined in /home/shared_typo3/typo3_source/typo3_src-6.2.0/typo3/sysext/core/Classes/Utility/ArrayUtility.php line 531 | TYPO3\\CMS\\Core\\Error\\Exception thrown in file /home/shared_typo3/typo3_source/typo3_src-6.2.0/typo3/sysext/core/Classes/Error/ErrorHandler.php in line 108. Requested URL: http://***/typo3/backend.php
```

Any Ideas?

**Comment by NamelessCoder** [comment] 2014-06-11 12:34
Hi Denys,

Could very well be an incompatible extension or another problem causing the LLL array to become invalid. Do you think you can track down _which_ extension is causing this error, by selectively uninstalling or blacklisting extensions in your site? If the problem is an incompatibility you can work around it by blacklisting that extension or only whitelisting your own. If it is caused by an unexpected format of LLL we can solve this but would need to know _how_ it is becoming invalid - and knowing one or more extension keys which cause the problem would certainly help :)

**Comment by NamelessCoder** [comment] 2014-08-03 21:13
I'll take the liberty of closing this one since incompatible extensions should be blacklisted. If you discover which exact extension key is causing this then I'd be happy to include it in the shipped blacklist ;)

**Closed as completed by NamelessCoder** 2014-08-03 21:13 UTC
